SELECT ID,  ((YEAR(FINISH_DATE) - YEAR(START_DATE))*12)+(MONTH(FINISH_DATE) - MONTH(START_DATE)) MONTH_COUNT
from PROJECT 
WHERE ((YEAR(FINISH_DATE) - YEAR(START_DATE))*12)+(MONTH(FINISH_DATE) - MONTH(START_DATE))  = 
(
	SELECT ((YEAR(FINISH_DATE) - YEAR(START_DATE))*12)+(MONTH(FINISH_DATE) - MONTH(START_DATE)) MONTH_COUNT
	from PROJECT 
	ORDER BY ((YEAR(FINISH_DATE) - YEAR(START_DATE))*12)+(MONTH(FINISH_DATE) - MONTH(START_DATE)) DESC
	LIMIT 1
)