(SELECT 'TYPE' ,NAME, BIRTHDAY 
FROM WORKER 
LIMIT 0)
UNION
	SELECT 'YOUNGEST' ,NAME, BIRTHDAY 
	FROM WORKER 
	WHERE BIRTHDAY IN (
		SELECT BIRTHDAY 
		FROM WORKER 
		ORDER BY BIRTHDAY DESC
		LIMIT 1
		)
		UNION
			SELECT 'ELDEST' ,NAME, BIRTHDAY 
			FROM WORKER 
			WHERE BIRTHDAY IN (
				SELECT BIRTHDAY 
				FROM WORKER 
				ORDER BY BIRTHDAY
				LIMIT 1
				)