SELECT ID,  ((((YEAR(FINISH_DATE) - YEAR(START_DATE))*12)+(MONTH(FINISH_DATE) - MONTH(START_DATE))) *
	(SELECT SUM(SALARY) 
	FROM WORKER 
	WHERE ID IN (
		SELECT WORKER_ID  
		FROM PROJECT_WORKER 
		WHERE PROJECT_ID IN (PROJECT .ID)
		)))PRICE
from PROJECT
ORDER BY ((((YEAR(FINISH_DATE) - YEAR(START_DATE))*12)+(MONTH(FINISH_DATE) - MONTH(START_DATE))) *
	(SELECT SUM(SALARY) 
	FROM WORKER 
	WHERE ID IN (
	SELECT WORKER_ID  
	FROM PROJECT_WORKER 
	WHERE PROJECT_ID IN (PROJECT .ID)
	))) DESC


